# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: professionalprac
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: devops
# "service" is the name of this project. This will also be added to your AWS resource names.
service: sharon-devops

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1

resources:
  Resources:
    S3Bucket:
      Type: 'AWS::S3::Bucket'
      Properties:
        BucketName: professional-practice-${opt:stage, 'staging'}


functions:
  deploy:
    handler: handler.deploy
    events:
      - s3:
          bucket: professional-practice-${opt:stage, 'staging'}
          event: s3:ObjectCreated:Put
          existing: true

package:
  include:
    - dist/**
  exclude:
    - node_modules/**
    - .git/**
    - .vscode/**
    - tests/**
    - coverage/**
    - docs/**
    - logs/**
    - '*.md'

plugins:
  - serverless-s3-sync

custom:
  s3Sync:
    - bucketName: professional-practice-${opt:stage, 'staging'}
      localDir: dist




